### ISSUE TITLE
ModuleNotFoundError: No module named 'concordex_map'

### ISSUE THREAD

**Issue by aaronkwc** [pachterlab/concordex#5]
Hello,

I successfully installed concordex using the command line from README. However, this error pops up when I call concordex on the command line:

```
(default_env) bash-4.4$ concordex -h
Traceback (most recent call last):
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/bin/concordex", line 33, in <module>
    sys.exit(load_entry_point('concordex==0.0.1', 'console_scripts', 'concordex')())
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/bin/concordex", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/lib/python3.9/site-packages/concordex/main.py", line 5, in <module>
    from .concordex_stat import setup_stat_args, validate_stat_args
  File "/mnt/beegfs/users/akwok/miniconda3/envs/default_env/lib/python3.9/site-packages/concordex/concordex_stat.py", line 6, in <module>
    from concordex_map import concordex_map 
ModuleNotFoundError:` No module named 'concordex_map'
```

Also tried to install via cloning the repo, i.e.:

`python setup.py install`

But ran into the same error. Could this be a versioning problem?

Thanks!

**Comment by kayla-jackson** [comment]
Hi @aaronkwc, it's almost certainly an issue with versioning. I'll work on a fix today. Thanks for bringing this to my attention.

**Comment by kayla-jackson** [comment]
Hi @aaronkwc, I've made some major changes to the code, and I'm working on writing new documentation + examples this week. In any case, this issue is resolved and the install with `pip install git+https://github.com/pachterlab/concordex.git` should work now.

**Comment by sidwekhande** [comment]
Hi, I am facing a similar issue and cannot import `concordex.concordex_map` after using the install command above. 

```
(venv) jupyter@cbd1437fc4ad:~/test-concordec$ python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import concordex
>>> concordex.__version__
'1.0.2'
>>> from concordex.concordex_map import concordex_map
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'concordex.concordex_map'
```

Are the new docs + examples available? I am interested in using the functions in the [example notebook](https://github.com/pachterlab/concordex/blob/main/examples/concordex_py_pbmc_demo.ipynb). Thanks!

**Comment by kayla-jackson** [comment]
Hi @sidwekhande, 

I've updated the [PBMC example notebook](https://github.com/pachterlab/concordex/blob/dcb447bc64c5fcb13af8b22d13c33c1ff50734bc/examples/concordex_py_pbmc_demo.ipynb). The interface has changed considerably and the `concordex_map()` function has been depreciated. 

All of the functionality of `concordex_map()` has been wrapped into `concordex.tools.calculate_concordex()` 

I hope this helps!

**Comment by sidwekhande** [comment]
Thanks @kayla-jackson, that's really helpful!
